In [41]:
# Librerías básicas

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statistics as std
import random as rd

pd.set_option('display.max_columns', None)
seed = 100

%matplotlib inline

In [42]:
df = pd.read_csv('relaciones_limpio.csv', sep = ';')

In [43]:
df.head()

,ESTU,CUES,CCAA,PROV,MUN,CAPITAL,TAMUNI,ENTREV,TIPO_TEL,SEXO,SEXO_NOMBRE,ORIENTACION,PAREJA,FELICIDAD,UNION_FISICA,UNION_EMOCIONAL,EDAD,EDAD_RANGO,P0,P1_1,P1_2,P1_3,P2_1,P2_2,P2_3,P2_4,P3_1,P3_2,P3_3,P3_4,P3_5,P3_6,P3_7,P3_8,P4_1,P4_2,P4_3,P4_4,P5,P5A_1,P5A_2,P5A_3,P5A_4,P5A_5,P5A_6,P5A_7,P6_1,P6_2,P6_3,P6_4,P6_5,P7_1,P7_2,P7_3,P7_4,P7_5,P7_6,P7_7,P7_8,P8,P8AMES,P8AANNO,P8B,P9_1,P9_2,P9_3,P9_4,P9_5,P10_1,P10_2,P10_3,P10_4,P10_5,P11,P12,P13_1,P13_2,P13_3,P13_4,P13_5,P13_6,P13_7,P13_8,P14_1,P14_2,P14_3,P14_4,P14_5,P15,P16,P17_1,P17_2,P17_3,P18_1,P18_2,P18_3,P18_4,P18_5,P18_6,P18_7,P19,P20,ESCIDEOL,PARTICIPACIONG,RECUVOTOG,SITLAB,CNO11,SITCONVIVEN,ESCUELA,NIVELESTENTREV,RELIGION,FRECUENCIARELIGION,CLASESOCIAL,P29_1,P29_2,P29A_1,P29A_2,IA_I501,IA_I502,IA_I503,IA_I504,IA_I505,IA_I506,IA_I507,IA_I508,IA_I509,IA_I510,IA_I511,IA_I512,IA_I513,IA_I514,IA_I515,IA_I516,IA_I517,IA_I518,IA_I519,IA_I520,IA_I521,IA_I522,IA_I523,IA_I524,IA_I525,IA_I526,IA_I528,IA_I529,IA_I530,IA_I531,IA_I532,IA_I533,IA_I534,IA_I535,IA_I536,IA_I537,IA_I538,IA_I539,IA_I540,IA_I541,IA_I542,IA_I543,IA_OBS0,IA_OBS1,IA_OBS2,IA_E1_DIA,IA_E1_MES,IA_E1_ANYO,IA_E2,IA_E3,IA_E4,IA_VALIDA,IA_APLAZADA,IA_MODIFICADA,IA_SUPERVISADA,IA_C2,IA_C2A,IA_C2B_1,IA_C2B_2,IA_C2B_3,IA_C2B_4,IA_C2B_5,IA_C2B_6,IA_C2B_7,IA_C2B_8,IA_C2B_9,IA_C2B_10,IA_C2B_11,IA_C2B_12,IA_C2B_13,IA_C2B_14,IA_C2B_15,IA_C2B_16,IA_C2B_17,IA_C2B_18,IA_C2B_19,IA_C2B_20,IA_C2B_21,IA_C2B_22,IA_C2B_23,IA_C2B_24,IA_C2B_25,IA_C3,IA_C4,P8A,RECUVOTOGR,RECUERDO,CNO11R,ESTUDIOS,RELIGIONR,CLASESUB
0,3325,1,1,4,0,3,3,0,2,1,Hombre,Heterosexual,Con pareja,7,10,10,36,36-38,1,10,7,10,1,1,1,2,1,1,5,1,5,1,8,5,8,10,8,6,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,3,3,7,2,3,2,2,1,3,1,2,2,7,1,0.0,11.0,1.0,1.0,1.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,10.0,10.0,4,5,4,2,5,2,1,2,3,2,2,2,2,5,3,3,3,3,4,1,4,4,4,2,3,1,7,5,5,NaN,1,2.0,3,3,8.0,4,NaN,3,1,2,3.0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,28,5,21,5,22,2,1,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,132.0,NaN,97,2,6,4,2
1,3325,2,1,4,13,2,5,0,2,1,Hombre,Heterosexual,Con pareja,9,2,8,51,51-53,1,8,9,9,2,2,1,8,1,1,1,3,1,5,7,1,7,10,10,10,1,1.0,1.0,1.0,1.0,9.0,1.0,2.0,3,3,3,1,3,5,5,5,5,5,5,5,1,1,0.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,8.0,4,4,3,2,5,5,2,1,3,2,2,2,2,99,2,3,3,3,2,1,3,3,4,2,3,1,9,8,1,1.0,1,1.0,1,3,11.0,1,1.0,98,1,1,2.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,28,5,21,5,18,2,1,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,36.0,1.0,1,1,6,1,8
2,3325,3,1,4,13,2,5,0,2,2,Mujer,Heterosexual,Soltero/a,8,0,0,61,60-62,1,10,9,97,1,1,1,2,7,7,7,7,1,3,7,7,10,10,10,97,1,1.0,1.0,2.0,7.0,7.0,2.0,7.0,1,3,7,1,3,4,2,2,5,97,2,7,97,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,2,2,5,5,2,1,1,4,1,1,1,1,7,4,7,7,7,7,7,7,7,7,7,7,1,8,3,1,2.0,2,NaN,9,3,11.0,6,NaN,4,2,2,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,28,5,21,5,18,2,1,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,2.0,2,12,6,4,3
3,3325,4,1,4,13,2,5,0,1,1,Hombre,Heterosexual,Con pareja,8,10,9,70,69-71,1,9,9,9,2,2,2,2,98,98,98,98,98,98,98,98,3,5,3,97,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,7,2,2,1,7,6,4,1,2,7,97,1,0.0,40.0,1.0,7.0,7.0,3.0,3.0,3.0,2.0,1.0,1.0,2.0,1.0,10.0,9.0,2,8,2,4,2,4,2,2,9,2,2,2,3,5,8,3,3,3,4,3,4,4,4,0,4,1,8,4,1,21.0,2,NaN,4,3,12.0,6,NaN,3,2,2,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,0,0,0,0,1,6,21,2,17,1,1,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,480.0,21.0,21,12,6,4,2
4,3325,5,1,4,13,2,5,0,2,1,Hombre,Heterosexual,Con pareja,10,7,10,24,24-26,1,10,10,10,2,2,1,1,5,8,5,5,5,2,7,5,5,10,10,7,1,1.0,1.0,2.0,1.0,2.0,1.0,2.0,3,1,7,1,3,1,1,97,3,97,1,7,3,1,10.0,0.0,1.0,1.0,7.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,10.0,1,2,1,1,1,2,2,4,4,1,1,1,1,5,1,3,3,3,4,1,4,4,4,0,3,1,10,4,5,NaN,1,4.0,4,3,6.0,4,NaN,2,1,2,2.0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,6,21,2,19,2,1,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,10.0,NaN,97,4,4,4,1

# Pregunta 1

**¿Tener una relación puede afectar a la percepción que se tiene del uso de internet?**

In [44]:
# Excluimos registros con NaN en la opinión sobre internet

df1 = df[ df["P16"] < 6 ]

In [45]:
rangos_edades = sorted(list(set(df["EDAD_RANGO"])))

In [46]:
opinion_media_16_soltero = []
opinion_media_16_pareja = []

In [47]:
for ages in rangos_edades:
    
    p = list( df1[ ( df1["EDAD_RANGO"]==ages ) & ( df1["PAREJA"]=='Con pareja') ]["P16"])
    s = list( df1[ ( df1["EDAD_RANGO"]==ages ) & ( df1["PAREJA"]=='Soltero/a') ]["P16"])
    
    opinion_media_16_pareja.append(std.mean(p))
    opinion_media_16_soltero.append(std.mean(s))

In [48]:
# Creamos el dataframe de opinion sobre uso de internet según relación

df1_opinion = pd.DataFrame()

df1_opinion["edad"] = rangos_edades
df1_opinion["solteros"] = opinion_media_16_soltero
df1_opinion["con pareja"] = opinion_media_16_pareja

df1_opinion

     edad  solteros  con pareja
0   18-20  2.414634    2.266667
1   21-23  2.687500    2.362069
2   24-26  2.583333    2.453125
3   27-29  2.379310    2.303797
4   30-32  2.739130    2.341176
5   33-35  2.416667    2.448980
6   36-38  3.727273    2.411765
7   39-41  2.580645    2.719424
8   42-44  2.933333    2.660000
9   45-47  3.315789    2.592920
10  48-50  2.750000    2.683453
11  51-53  2.851852    2.782609
12  54-56  2.918919    2.758065
13  57-59  2.958333    2.719626
14  60-62  3.292683    3.135135
15  63-65  3.488372    3.109890
16  66-68  3.351351    3.460674
17  69-71  3.511628    3.388235
18  72-74  3.217391    3.409091
19  75-77  3.666667    3.516667
20  78-80  3.428571    3.307692
21  81-83  3.357143    4.142857
22  84-86  3.100000    4.500000
23  87-89  3.333333    4.333333
24  90-92  4.333333    5.000000

In [49]:
# df1_opinion.to_csv('df1_opinion.csv')

# Pregunta 2

**¿La satisfacción en la vida familiar afecta a la satisfacción en distintos campos relacionados a la vida social o afectiva?**

In [50]:
# Excluimos outliers

df2 = df[ (df["P1_1"]<15) & (df["P1_2"]<15) & (df["P1_3"]<15) ]

In [51]:
indices = list(range(0,len(df2)))

In [52]:
# Barajamos lista de índices

rd.shuffle(indices)

In [53]:
len(indices)

2332

In [54]:
re = []

for i in range(1,len(indices)):
    
    if len(indices)%i == 0:
        re.append(i)

print(re)

[1, 2, 4, 11, 22, 44, 53, 106, 212, 583, 1166]

In [55]:
# Agruparemos 44 grupos con 53 muestras aleatorias cada uno

2332/44

53.0

In [56]:
rel_familia = []
rel_social = []
rel_afectiva = []

i = 5

while ( i < len(indices) ):
    
    j = 0
    aux_f = []
    aux_s = []
    aux_a = []
    
    while ( j < 53 ):
        
        aux_f.append(list(df2["P1_1"])[indices[0]])
        aux_s.append(list(df2["P1_2"])[indices[0]])
        aux_a.append(list(df2["P1_3"])[indices[0]])
        
        indices.pop(0)
        j = j + 1
        
    rel_familia.append(std.mean(aux_f))
    rel_social.append(std.mean(aux_s))
    rel_afectiva.append(std.mean(aux_a))

In [57]:
# Creamos el dataframe de opinion sobre uso de internet según relación

df2_satisfaccion = pd.DataFrame()

df2_satisfaccion["familia"] = rel_familia
df2_satisfaccion["social"] = rel_social
df2_satisfaccion["afectiva"] = rel_afectiva

df2_satisfaccion

     familia    social  afectiva
0   9.000000  8.415094  8.905660
1   8.735849  8.471698  8.792453
2   8.603774  8.000000  8.660377
3   8.867925  8.584906  9.000000
4   8.471698  8.339623  8.924528
5   8.301887  7.396226  8.716981
6   8.735849  8.490566  8.792453
7   9.018868  8.660377  9.037736
8   8.679245  8.339623  8.415094
9   8.886792  8.245283  8.509434
10  8.943396  8.547170  8.679245
11  8.754717  8.339623  8.660377
12  8.566038  8.339623  8.698113
13  8.679245  8.452830  8.547170
14  9.150943  8.245283  9.075472
15  9.000000  8.528302  9.169811
16  8.490566  7.943396  8.471698
17  9.037736  8.320755  9.207547
18  9.000000  8.641509  8.943396
19  8.886792  8.622642  8.981132
20  8.981132  8.566038  8.962264
21  8.886792  8.169811  8.754717
22  8.792453  8.452830  9.132075
23  8.830189  7.886792  8.660377
24  8.849057  8.358491  8.566038
25  8.716981  8.528302  8.490566
26  8.698113  8.433962  8.981132
27  8.943396  8.584906  8.415094
28  8.905660  8.396226  8.792453
29  8.396226  7.754717  8.264151
30  8.566038  8.264151  8.528302
31  8.811321  8.547170  8.924528
32  9.113208  8.603774  9.188679
33  8.943396  8.566038  9.150943
34  9.018868  8.377358  9.226415
35  8.415094  8.452830  8.641509
36  8.566038  8.452830  8.792453
37  8.584906  8.245283  8.792453
38  8.849057  8.415094  8.660377
39  8.886792  8.679245  8.566038
40  8.792453  8.056604  8.547170
41  8.981132  8.339623  8.943396
42  8.660377  8.056604  8.490566
43  8.981132  8.245283  9.113208

In [58]:
# df2_satisfaccion.to_csv('df2_satisfaccion.csv')

# Pregunta 3

**¿Cómo son de satisfactorias las relaciones afectivas según el nivel de estudios de cada 
componente de la pareja? ¿y según a su situación laboral?**

In [59]:
df3 = df[ ( df["CLASESUB"] <= 5 ) & ( df["ESTUDIOS"] <= 6 ) ]

In [60]:
clase = ["alta y media alta", "media-media", "media-baja", "trabajadora/obrera/ploretario", "baja/pobre"]
estudios = ["sin estudios", "primaria", "secundaria", "bachillerato", "FP", "superiores"]

clase_i = []
estudios_i = []

In [61]:
for i, x in enumerate(df3["CLASESUB"]):
    
    clase_i.append(clase[x-1])
    
for j, y in enumerate(df3["ESTUDIOS"]):
    
    estudios_i.append(estudios[y-1])

In [62]:
# Creamos el dataframe 

df3_estudios_clasesocial = pd.DataFrame()

df3_estudios_clasesocial["genero"] = df3["SEXO_NOMBRE"]
df3_estudios_clasesocial["edad"] = df3["EDAD_RANGO"]
df3_estudios_clasesocial["afectiva"] = df3["P1_3"]
df3_estudios_clasesocial["clase_social"] = clase_i
df3_estudios_clasesocial["nivel_estudios"] = estudios_i

In [63]:
df3_estudios_clasesocial = df3_estudios_clasesocial[df3_estudios_clasesocial["afectiva"] < 11]

In [64]:
df3_estudios_clasesocial

      genero   edad  afectiva       clase_social nivel_estudios
0     Hombre  36-38        10        media-media     superiores
3     Hombre  69-71         9        media-media     superiores
4     Hombre  24-26        10  alta y media alta   bachillerato
5      Mujer  51-53         5        media-media     superiores
6     Hombre  60-62        10         media-baja     secundaria
...      ...    ...       ...                ...            ...
2966  Hombre  39-41        10        media-media             FP
2967   Mujer  39-41        10        media-media     secundaria
2969   Mujer  36-38        10        media-media     superiores
2970  Hombre  30-32        10        media-media     superiores
2971   Mujer  24-26         7        media-media     superiores

[2141 rows x 5 columns]

In [65]:
# df3_estudios_clasesocial.to_csv('df3_estudios_clasesocial.csv')